
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StoreProvider from "@/store/providers/StoreProvider"
import ThemeModeProvider from '@/store/providers/ThemeProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<ThemeModeProvider>
				<StoreProvider>
					<body className={inter.className}>
						{children}
					</body>
				</StoreProvider>
			</ThemeModeProvider>
		</html>
	)
}